export const SET_VEHICLES="SET_VEHICLES";

export const FOCUS_VEHICLE="FOCUS_VEHICLE";

export const UNFOCUS_VEHICLE="UNFOCUS_VEHICLE";

export const RECENTER_MAP="RECENTER_MAP";

export const RECENTER_MAP_FINISH="RECENTER_MAP_FINISH";

export const SET_TIMEOUT="SET_TIMEOUT";

export const CLEAR_TIMEOUT="CLEAR_TIMEOUT";


export const EDIT_POPUP="EDIT_POPUP";
export const TRIPS_POPUP="TRIPS_POPUP";
export const ROUTE_POPUP="ROUTE_POPUP";
export const NO_POPUP="NO_POPUP";

export const TOGGLE_FILTER_POPUP="TOGGLE_FILTER_POPUP";