export const EXPAND_SIDEBAR="EXPAND_SIDEBAR";
export const SET_IS_MOBILE="SET_IS_MOBILE";
export const SET_VEHICLES="SET_VEHICLES";

export const SET_SHOWING_TRIP="SET_SHOWING_TRIP";

export const FOCUS_VEHICLE="FOCUS_VEHICLE";

export const UNFOCUS_VEHICLE="UNFOCUS_VEHICLE";

export const RECENTER_MAP="RECENTER_MAP";

export const RECENTER_MAP_FINISH="RECENTER_MAP_FINISH";

export const SET_TIMEOUT="SET_TIMEOUT";

export const CLEAR_TIMEOUT="CLEAR_TIMEOUT";


export const EDIT_POPUP="EDIT_POPUP";
export const TRIPS_POPUP="TRIPS_POPUP";
export const ROUTE_POPUP="ROUTE_POPUP";
export const NO_POPUP="NO_POPUP";

export const TOGGLE_FILTER_POPUP="TOGGLE_FILTER_POPUP";

export const SET_FILTER_ACTIVE="SET_FILTER_ACTIVE";

export const SET_REFRESH_METHOD="SET_REFRESH_METHOD";
export const REFRESH_VEHICLES="REFRESH_VEHICLES";


export const UPDATE_VEHICLE_DATA="UPDATE_VEHICLE_DATA";


export const UPDATE_ALARM_DATA="UPDATE_ALARM_DATA";

export const SET_ROUTE="SET_ROUTE";

export const SELECT_VEHICLE_POSITION="SELECT_VEHICLE_POSITION";
export const GET_VEHICLE_POSITION="GET_VEHICLE_POSITION";